### ISSUE TITLE
1.17v 6.0.0

### ISSUE THREAD

**Issue by Jkosio23** [shedaniel/LightOverlay-Fabric#100]
Whenever enabled, the console is spammed with the number 1 once per line. https://paste.ee/p/qeWGd

**Comment by shedaniel** [comment]
Oops! Left my debug code in!

**Comment by A-UNDERSCORE-D** [comment]
Ah it is your code okay. Was just looking around to see if I could find it.

**Comment by Jkosio23** [comment]
is there going to be a patch for this soon?

**Comment by shedaniel** [comment]
Yes, along with other optimisations.

**Comment by MestreLion** [comment]
> Yes, along with other optimisations.

So, what exactly is being published in CurseForge as "LightOverlay 6.0.1 for MC 1.17.1"? I couldnt find a the 6.0.1 commit in the repository. Are the CurseForge releases for 1.17.1 coming from your `1.16.2` branch? Does it include the commit 5b36cf6b846515145dc1f93e4f8e9ea108420090 ? It's a bit hard to match CureForge releases andcommits without some repository tags.
