### ISSUE TITLE
Light overlay only working in a line

### ISSUE THREAD

**Issue by JakubVymetal** [shedaniel/LightOverlay-Fabric#102]
I am running the Fabric modpack Fabulously optimised 1.17, and i added Light overlay for both me and my friend, but the overlay only renders on x-1, so it basically only works in one line across the world... I think the 1.17 version is having problems with canvas render again

![image](https://user-images.githubusercontent.com/10184942/123460436-e9b44800-d5e7-11eb-8d94-204895c46061.png)

**Comment by shedaniel** [comment]
Try updating canvas
