### ISSUE TITLE
Doesn't work in all my worlds

### ISSUE THREAD

**Issue by MegaMMC** [shedaniel/LightOverlay-Fabric#11]
I have 2 worlds, and I play on 2 servers, the 2 servers and one of my worlds the mod works fine, but the other map that I have.... I can press F7 as many times as I want and the mod just doesn't do anything

**Comment by shedaniel** [comment]
Was this issue fixed?

**Comment by MegaMMC** [comment]
Yes, I was just dumb, your mod wasn't showing because I was on the Void biome and mobs don't spawn.
