### ISSUE TITLE
unable to run / crash on startup on mod version 6.0.0 with Fabric 1.17.1

### ISSUE THREAD

**Issue by h3oCharles** [shedaniel/LightOverlay-Fabric#112]
im failing to load the game with version 6.0.0 on fabric version 0.11.6 for mc1.17.1, saying that version 0.29.1 or higher, but there's no version like that... right?

https://pastebin.com/JbJNFdWs

after fiddling with files a bit, I managed to find a line in fabric.mod.json file that indicated the required fabric version. i deleted it, and got a different crash

https://pastebin.com/RHpnWWdc
https://pastebin.com/D0j42AFQ
https://pastebin.com/zfuCPNRP

rest of the needed mods are in the pastes

**Comment by shedaniel** [comment]
you are not supposed to delete that line, also “there is no versions higher than that”: 
![IMG_0438](https://user-images.githubusercontent.com/34910653/126064738-27b79a39-43d9-443b-9afb-0a45dc1160ab.jpeg)

**Comment by h3oCharles** [comment]
yes, i know im not really supposed to do that, I was doing that for debugging purposes
I didn't know there were newer versions than that, MultiMC version picker didn't have anything higher than 0.11.6

appreciate the fast response tho
