### ISSUE TITLE
Startup crash if used with this modpack

### ISSUE THREAD

**Issue by Tyfaspo** [shedaniel/LightOverlay-Fabric#120]
So I tried installing this mod with this [modpack](https://www.curseforge.com/minecraft/modpacks/speed-of-light-fps-booster-sol), and it crashes at startup.

Crash error:
https://imgur.com/a/F3EbM4K

Crash log:
[latest.log](https://github.com/shedaniel/LightOverlay/files/7159496/latest.log)

**Comment by shedaniel** [comment]
Install architectury

**Comment by Tyfaspo** [comment]
Sorry, I'm a little bit dumb
