### ISSUE TITLE
Show numbers/cross only on dangerous areas

### ISSUE THREAD

**Issue by Madis0** [shedaniel/LightOverlay-Fabric#127]
Since in 1.18 mobs don't spawn on any light level above 0, it would be useful to have an option where only 0 (or user-defined threshold) is rendered at all, whether as a cross or number. 
This would work well with #93 while keeping good performance.

**Comment by TakingItCasual** [comment]
This can be done from the mod config by setting "Secondary Light Level" to "0". Although this should probably be changed to the default behavior from 1.18 onwards.

**Comment by Madis0** [comment]
Thanks, so:
* Light Level: 0
* Secondary Light Level: 0
* Show Number Instead: No

achieved the result. But keeping the issue open as it could be a default indeed.

**Comment by shedaniel** [comment]
No, this behaviour is specifically tweaked to be like this for 1.18, because spawners uses 7

**Comment by Madis0** [comment]
But that was reverted? https://minecraft.fandom.com/wiki/Spawner#History

**Comment by shedaniel** [comment]
Yes, it was changed from 7 to 12, and reverted back to 7
