### ISSUE TITLE
Marker on wrong location

### ISSUE THREAD

**Issue by MelanX** [shedaniel/LightOverlay-Fabric#13]
Version: 4.0
MC: 19w35a
Fabric: 0.3.2 build 217-1.15

![image](https://user-images.githubusercontent.com/26039509/64201044-0240f480-ce8e-11e9-9eaf-f71320324a55.png)
Grass has markers for spawning :) Impossible I guess :D

**Comment by shedaniel** [comment]
This is intended

**Comment by shedaniel** [comment]
Mobs can spawn on grass
