### ISSUE TITLE
Easier use of the secondary light level

### ISSUE THREAD

**Issue by RoyDubnium** [shedaniel/LightOverlay-Fabric#135]
I don't know what the secondary light level was designed to do, but i can't seem to get it to work the way i want. I am attempting to have it render normally, with light level 0 as the mob spawn level, but also to render the blocks with a light level of 1-7 in the secondary colour. Whatever I do, i can't get it to work in this way. It either renders everything as the secondary colour, or nothing.
![2022-01-13_19 19 23](https://user-images.githubusercontent.com/72664566/149395647-8b6177bb-2509-4cba-8bd2-67932f0a07a1.png)
Attached is an example of what happens. Is there any way you could fix this, or advise me on how to get it working how i need it?

**Comment by BlueA10** [comment]
From the CurseForge page:

> A yellow cross means that mobs can spawn at night, a red cross means that mobs can spawn anytime.
> 
> A blue cross means that mobs can spawn if there is a spawner (1.18 only)

You can turn off the blue crosses entirely by setting the secondary light level slider all the way to the left (Off).

**Comment by prenetic** [comment]
I'm with @O3nboi on this one, the provided text doesn't clear things up for me. I know I can disable the secondary light level behavior, but I'd like to better understand how to properly use this feature. For example, with the default configuration in 1.19 this paints the unlit outdoors in blue, which doesn't match the description (mobs can spawn if there is a spawner).
