### ISSUE TITLE
Failed to create mod instance NoClassDefFoundError AbstractConfigListEntry

### ISSUE THREAD

**Issue by frakier** [shedaniel/LightOverlay-Fabric#14]
forge-1.14.4-28.1.68
LightOverlay-3.6.jar
no other mods, debug.log attached {I did a little obfuscation of player name and such but should not hinder you otherwise}

Failed to create mod instance. ModID: lightoverlay-forge, class me.shedaniel.lightoverlay.LightOverlay
java.lang.NoClassDefFoundError: me/shedaniel/forge/clothconfig2/api/AbstractConfigListEntry

[debug.log](https://github.com/shedaniel/LightOverlay-Fabric/files/3775477/debug.log)

**Comment by shedaniel** [comment]
[Cloth Config Forge](https://www.curseforge.com/minecraft/mc-mods/cloth-config-forge) is required
