### ISSUE TITLE
Not working at all on Fabric/1.18.2

### ISSUE THREAD

**Issue by FuzzyThailand** [shedaniel/LightOverlay-Fabric#147]
New setup, only has latest versions of Fabric, Architectury API, Cloth Config API, Light Overlay and Mod Menu.

Light Overlay does seem to be doing nothing at all:
- F7 doesn't work
- Mod Menu shows no Settings option
- Key binds shows nothing 
- 
This is the startup log: https://pastebin.com/7gb0SGYy

**Comment by yannick1124** [comment]
I'm having the same issue

**Comment by PIPILAN** [comment]
Me too

**Comment by shedaniel** [comment]
Did you accidentally download the forge version
