### ISSUE TITLE
Zombie pigmen spawning wrong

### ISSUE THREAD

**Issue by CGDoctor8** [shedaniel/LightOverlay-Fabric#17]
In the nether shows vaild as a invalid spawning location any light level that is 8+ when it should be 11

From the minecraft wiki: https://minecraft.gamepedia.com/Zombie_Pigman

> Any 2 block high space in light levels 11 and lower in the Nether

![image](https://user-images.githubusercontent.com/39572468/71199734-7a40f800-228e-11ea-8b36-b2c2e85f07fc.png)

**Comment by shedaniel** [comment]
This mod will always use Zombie as the mod to test for as default, another issue is opened at #21
