### ISSUE TITLE
See numbers through floor

### ISSUE THREAD

**Issue by Cmarullo308** [shedaniel/LightOverlay-Fabric#173]
On version 8.0.0 on 1.20.1 fabric you're able to see the numbers through the floor in the caves sometimes which is kinda annoying

![Screenshot](https://github.com/shedaniel/LightOverlay/assets/8798443/ff264dc4-5378-4bed-97d5-cad959b6cbe5)

**Comment by rozbrajaczpoziomow** [comment]
#168
