### ISSUE TITLE
Warning at launch - "uses 'requires' key in fabric.mod.json, which is not supported"

### ISSUE THREAD

**Issue by purplecho** [shedaniel/LightOverlay-Fabric#19]
Every time I launch via MultiMC I get the below warning in the log:

``[main/WARN]: Mod `lightoverlay` (4.1) uses 'requires' key in fabric.mod.json, which is not supported - use 'depends'``

It doesn't seem to be causing any current problems but I thought it worth flagging up in case compatibility gets broken in future Fabric versions.

Running MultiMC version 0.6.7-1316 with the latest Minecraft and Fabric (Minecraft 1.15.1 and Fabric version 0.7.3+build.176) as available through MultiMC.

**Comment by kamikamiha** [comment]
Has there been any update to this at all? I am running into the same issue myself currently.
