### ISSUE TITLE
Feature request: Draw light level on tilled ground

### ISSUE THREAD

**Issue by Bernasss12** [shedaniel/LightOverlay-Fabric#23]
Firstly I just wanna say that I've been testing the mod in 20w07a and I have expecienced no problems as of yet :)
As for the actual request I just wanted to ask if it would be possible to have light levels be drawn over farmland, the most useful mode would be the value mode since the it would be nice to check if every plant is currently at light level over 9.
Since the main focus of the mod is (at least from what I've noticed) to pinpoint spawn locations I know this isn't directly in the scope of the mod and in that case I would ask if it could be a configurable option maybe?

**Comment by shedaniel** [comment]
Added in v5.0 for 20w10a.
