### ISSUE TITLE
Crashes server on Startup

### ISSUE THREAD

**Issue by NielsPilgaard** [shedaniel/LightOverlay-Fabric#28]
Having this mod on a server, prevents it from starting.
Crash report: https://gist.github.com/NillerMedDild/39df7c63669b23332593f05891d2b364

**Comment by shedaniel** [comment]
You are using Light Level Overlay Reloaded. **Not** even this mod (Light Overlay).

**Comment by NielsPilgaard** [comment]
Oh god, sorry about that ^^'
