### ISSUE TITLE
Spawnable errors

### ISSUE THREAD

**Issue by xAlicatt** [shedaniel/LightOverlay-Fabric#3]
Scaffolds are not showing as spawnable,  and they are...I've seen mobs spawn on them multiple times and leaves are showing up as spawnable, which they are not. Will report back if I find more similar issues.

**Comment by shedaniel** [comment]
Leaves are spawnable, the current spawnable system sux i am trying to fix in the future

**Comment by xAlicatt** [comment]
The only thing I've seen spawn on leaves is Illager parties and they can spawn on anything that is open to sky afaik. Regular mobs cannot spawn on leaves. Am I missing something?

**Comment by shedaniel** [comment]
Currently remaking the mob spawning checks

**Comment by shedaniel** [comment]
They should all be fixed in version 1.2 :)
