### ISSUE TITLE
1.15.2 fabric - crash on launch

### ISSUE THREAD

**Issue by SunSerega** [shedaniel/LightOverlay-Fabric#33]
Mod version 4.3 (just downloaded).

[crash-2020-04-13_05.08.18-client.txt](https://github.com/shedaniel/LightOverlay-Fabric/files/4467689/crash-2020-04-13_05.08.18-client.txt)

I removed all other mods before getting this crash report.

**Comment by shedaniel** [comment]
install Fabric api
