### ISSUE TITLE
1.15.2 - mod loaded, but no in-game visuals shown

### ISSUE THREAD

**Issue by SunSerega** [shedaniel/LightOverlay-Fabric#34]
F7 just doesn't do anything for me.
And changing to other hotkey doesn't help:
https://youtu.be/EyNVT2Ik0U8

**Comment by shedaniel** [comment]
Video is private

**Comment by shedaniel** [comment]
Please send the logs.

**Comment by SunSerega** [comment]
> Video is private

Ah, sorry, forgot to confirm...

> logs

[latest.log](https://github.com/shedaniel/LightOverlay-Fabric/files/4468450/latest.log)

**Comment by shedaniel** [comment]
You are in the void biome, no mobs can spawn in that biome.
