### ISSUE TITLE
Light overlay do not show properly (due to cache?)

### ISSUE THREAD

**Issue by i0xHeX** [shedaniel/LightOverlay-Fabric#37]
**Reproduce steps:**

1. Turn on light overlay:
![2020-04-29_13 55 41](https://user-images.githubusercontent.com/33582973/80588600-50a89200-8a21-11ea-9227-ae07225cc8cd.png)
2. Turn off light overlay
3. Make block changes
4. Turn on light overlay:
![2020-04-29_13 56 03](https://user-images.githubusercontent.com/33582973/80588575-46869380-8a21-11ea-831f-c902183eca2e.png)

"Fixes" updating any block near.

**Comment by shedaniel** [comment]
Sounds like cache issues

**Comment by shedaniel** [comment]
Fixed in v4.6.1 or v5.2.1-unstable
