### ISSUE TITLE
Can't find mod settings?

### ISSUE THREAD

**Issue by ChildishGiant** [shedaniel/LightOverlay-Fabric#41]
I'm trying to change the settings and can't find them anywhere. On forge it says "Fabric 1.14+: Mod Menu > Config" but I can't find a mod menu button. Does this mean I need to install the [Mod Menu](https://github.com/Prospector/ModMenu) mod to use the settings?

**Comment by ChildishGiant** [comment]
Installing that mod shows the settings but surely you don't need another mod just to access the settings?

**Comment by shedaniel** [comment]
sadly you do, this is currently the annoying for fabric

**Comment by shedaniel** [comment]
edit: if you are on forge you should have access to it already

**Comment by ChildishGiant** [comment]
Ah so it's assumed one has this installed and there's probably a pending PR on fabric to merge this?

**Comment by shedaniel** [comment]
No, on Fabric you just install Mod Menu, there is already support for that.
