### ISSUE TITLE
Config Screen Minecraft 1.15 and ClothAPI

### ISSUE THREAD

**Issue by aarontigan** [shedaniel/LightOverlay-Fabric#42]
With the config screen being blocked with Minecraft 1.15 do we HAVE to have the ClothAPI installed as well? Seems pointless since we can't actually adjust any configs from in game in 1.15.

**Comment by shedaniel** [comment]
you can edit the configs, that's what cloth config is for.

**Comment by aarontigan** [comment]
Running Fabric yes you can edit them in game, but running Forge you have to edit configs manually from the config folder for Minecraft version 1.15. Unless I'm missing something somewhere where Cloth adds a screen somewhere in Forge version.

**Comment by shedaniel** [comment]
Cloth doesnt add a screen, but it provides a screen for light overlay to add a screen.

Open up the mod list added by forge and edit the screen.

**Comment by aarontigan** [comment]
Ah, I see it now. Idk how I missed that before. Now I wish more mods used Cloth API lol Sorry to bother you.

**Comment by shedaniel** [comment]
Don't worry, I also think it is a pity that most mods don't have a config screen because forge doesnt have one yet, I think when forge finally adds their config screen mods will start to use them.
