### ISSUE TITLE
Minecraft Fabric API crashes

### ISSUE THREAD

**Issue by razvanksz** [shedaniel/LightOverlay-Fabric#45]
Mod I use : Wurst 7.1.2
I use TLauncher,not official launcher.
When I try to start minecraft it crashes with exit code:1
In console:
[11:23:34] [main/INFO]: Loading for game Minecraft 1.16
> [11:23:35] [main/WARN]: Incomplete remapped file found! This means that the remapping process failed on the previous launch. If this persists, make sure to let us at Fabric know!
> [11:23:35] [main/INFO]: Fabric is preparing JARs on first launch, this may take a few seconds...
> Mapping source name conflicts detected:
>   dpp METHOD c (()V) -> [dpp/method_19366, dhv/method_20882]
>   dpx METHOD c (()V) -> [dpx/method_19366, dhv/method_20882]
>   djp METHOD c (()V) -> [djp/method_19366, dhv/method_20882]
>   dka METHOD c (()V) -> [dka/method_19366, dhv/method_20882]
>   dhv METHOD c (()V) -> [dhv/method_20882, dhv/method_19366]
>   djt METHOD c (()V) -> [djt/method_19366, dhv/method_20882]
>   dqo METHOD c (()V) -> [dqo/method_19366, dhv/method_20882]
>   dst METHOD c (()V) -> [dst/method_19366, dhv/method_20882]
>   dqi METHOD c (()V) -> [dqi/method_19366, dhv/method_20882]
>   eqd METHOD c (()V) -> [eqd/method_19366, dhv/method_20882]
>   dpr METHOD c (()V) -> [dhv/method_20882, dpr/method_19366]
>   drj METHOD c (()V) -> [drj/method_19366, dhv/method_20882]
>   dty METHOD c (()V) -> [dty/method_19366, dhv/method_20882]
>   dsp METHOD c (()V) -> [dsp/method_19366, dhv/method_20882]
>   dtb METHOD c (()V) -> [dtb/method_19366, dhv/method_20882]
>   djv METHOD c (()V) -> [djv/method_19366, dhv/method_20882]
>   dsx METHOD c (()V) -> [dhv/method_20882, dsx/method_19366]
>   dkg METHOD c (()V) -> [dkg/method_19366, dhv/method_20882]
>   dsa METHOD c (()V) -> [dsa/method_19366, dhv/method_20882]
>   dsl METHOD c (()V) -> [dsl/method_19366, dhv/method_20882]
>   dke METHOD c (()V) -> [dke/method_19366, dhv/method_20882]
>   dqx METHOD c (()V) -> [dqx/method_19366, dhv/method_20882]
>   dqu METHOD c (()V) -> [dqu/method_19366, dhv/method_20882]
>   dpo METHOD c (()V) -> [dpo/method_19366, dhv/method_20882]
>   dkl METHOD c (()V) -> [dkl/method_19366, dhv/method_20882]
>   dju METHOD c (()V) -> [dju/method_19366, dhv/method_20882]
>   djw METHOD c (()V) -> [djw/method_19366, dhv/method_20882]
>   djz METHOD c (()V) -> [djz/method_19366, dhv/method_20882]
>   dqm METHOD c (()V) -> [dqm/method_19366, dhv/method_20882]
>   dqk METHOD c (()V) -> [dhv/method_20882, dqk/method_19366]
>   djs METHOD c (()V) -> [dhv/method_20882, djs/method_19366]
>   dqv METHOD c (()V) -> [dqv/method_19366, dhv/method_20882]
>   dqa METHOD c (()V) -> [dqa/method_19366, dhv/method_20882]
>   dkd METHOD c (()V) -> [dkd/method_19366, dhv/method_20882]
>   dsk METHOD c (()V) -> [dsk/method_19366, dhv/method_20882]
>   dub METHOD c (()V) -> [dhv/method_20882, dub/method_19366]
>   dta METHOD c (()V) -> [dta/method_19366, dhv/method_20882]
>   dpm METHOD c (()V) -> [dpm/method_19366, dhv/method_20882]
>   eqb METHOD c (()V) -> [dhv/method_20882, eqb/method_19366]
>   dki METHOD c (()V) -> [dki/method_19366, dhv/method_20882]
>   dpy METHOD c (()V) -> [dpy/method_19366, dhv/method_20882]
>   dro METHOD c (()V) -> [dhv/method_20882, dro/method_19366]
>   dsc METHOD c (()V) -> [dsc/method_19366, dhv/method_20882]
>   duc METHOD c (()V) -> [duc/method_19366, dhv/method_20882]
>   djn METHOD c (()V) -> [djn/method_19366, dhv/method_20882]
>   dkk METHOD c (()V) -> [dkk/method_19366, dhv/method_20882]
>   dqd METHOD c (()V) -> [dqd/method_19366, dhv/method_20882]
>   dtz METHOD c (()V) -> [dtz/method_19366, dhv/method_20882]
>   dpl METHOD c (()V) -> [dpl/method_19366, dhv/method_20882]
>   djx METHOD c (()V) -> [djx/method_19366, dhv/method_20882]
>   djr METHOD c (()V) -> [djr/method_19366, dhv/method_20882]
>   dpz METHOD c (()V) -> [dpz/method_19366, dhv/method_20882]
>   dpw METHOD c (()V) -> [dpw/method_19366, dhv/method_20882]
>   dqz METHOD c (()V) -> [dhv/method_20882, dqz/method_19366]
>   dtg METHOD c (()V) -> [dtg/method_19366, dhv/method_20882]
>   drw METHOD c (()V) -> [drw/method_19366, dhv/method_20882]
>   dkh METHOD c (()V) -> [dhv/method_20882, dkh/method_19366]
>   dps METHOD c (()V) -> [dps/method_19366, dhv/method_20882]
>   drs METHOD c (()V) -> [drs/method_19366, dhv/method_20882]
>   dpu METHOD c (()V) -> [dpu/method_19366, dhv/method_20882]
>   dqs METHOD c (()V) -> [dqs/method_19366, dhv/method_20882]
>   dqc METHOD c (()V) -> [dqc/method_19366, dhv/method_20882]
>   dpq METHOD c (()V) -> [dhv/method_20882, dpq/method_19366]
>   dsj METHOD c (()V) -> [dhv/method_20882, dsj/method_19366]
>   dqw METHOD c (()V) -> [dqw/method_19366, dhv/method_20882]
>   dpn METHOD c (()V) -> [dpn/method_19366, dhv/method_20882]
>   dkm METHOD c (()V) -> [dkm/method_19366, dhv/method_20882]
>   dpk METHOD c (()V) -> [dpk/method_19366, dhv/method_20882]
>   dqh METHOD c (()V) -> [dqh/method_19366, dhv/method_20882]
>   dqy METHOD c (()V) -> [dqy/method_19366, dhv/method_20882]
>   drl METHOD c (()V) -> [drl/method_19366, dhv/method_20882]
>   djy METHOD c (()V) -> [dhv/method_20882, djy/method_19366]
>   dqt METHOD c (()V) -> [dqt/method_19366, dhv/method_20882]
>   dry METHOD c (()V) -> [dhv/method_20882, dry/method_19366]
>   dua METHOD c (()V) -> [dua/method_19366, dhv/method_20882]
>   drt METHOD c (()V) -> [drt/method_19366, dhv/method_20882]
>   dsm METHOD c (()V) -> [dsm/method_19366, dhv/method_20882]
>   dkj METHOD c (()V) -> [dkj/method_19366, dhv/method_20882]
>   dsq METHOD c (()V) -> [dsq/method_19366, dhv/method_20882]
>   dkc METHOD c (()V) -> [dkc/method_19366, dhv/method_20882]
>   dru METHOD c (()V) -> [dhv/method_20882, dru/method_19366]
>   dpv METHOD c (()V) -> [dhv/method_20882, dpv/method_19366]
>   djq METHOD c (()V) -> [djq/method_19366, dhv/method_20882]
>   djo METHOD c (()V) -> [djo/method_19366, dhv/method_20882]
>   dsb METHOD c (()V) -> [dsb/method_19366, dhv/method_20882]
>   drn METHOD c (()V) -> [drn/method_19366, dhv/method_20882]
>   drg METHOD c (()V) -> [drg/method_19366, dhv/method_20882]
>   dpj METHOD c (()V) -> [dpj/method_19366, dhv/method_20882]
>   drm METHOD c (()V) -> [drm/method_19366, dhv/method_20882]
>   drq METHOD c (()V) -> [drq/method_19366, dhv/method_20882]
>   dkb METHOD c (()V) -> [dkb/method_19366, dhv/method_20882]
Here I am!
[VersionManager] Refreshing versions locally...
[VersionManager] Versions has been refreshed (74 ms)
[Launcher] Minecraft closed with exit code: 1
[Launcher] Launcher exited.

**Comment by shedaniel** [comment]
I do not support cracked Minecraft or hacked clients
