### ISSUE TITLE
Activating Light Levels takes up all the FPS

### ISSUE THREAD

**Issue by HendrikJ79** [shedaniel/LightOverlay-Fabric#46]
Minecraft: 1.16 Fabric
Version: 5.3.0 Fabric

When activating light levels in the world it takes up al the FPS, not seen any errors in logs.
Game not fully loading CPU or RAM so this is not the issue.

**Comment by shedaniel** [comment]
Can you send your config file

**Comment by HendrikJ79** [comment]
I have temporary downgraded to 5.2.2-unstable wich is working fine

Also my config file: [lightoverlay.txt](https://github.com/shedaniel/LightOverlay/files/4825214/lightoverlay.txt)

**Comment by shedaniel** [comment]
Look in the settings screen of Light Overlay, caching is now disabled by default, and is important to have it enabled if your LO reach is higher than 24.

Your LO reach is 64.

**Comment by HendrikJ79** [comment]
Thanks, that works with some loss of FPS (Low-End PC) but good playable.
What does Secondary Light Level? Does it disable numbers or crosses below this setting?

**Comment by shedaniel** [comment]
if you set your Secondary Light Level to like 2, light levels from 0 to 1 will be red, 2 to 6 will be **blue**, 7 and above will be yellow

**Comment by HendrikJ79** [comment]
Thank you, that's a  nice option.
A suggestion to update the changelog to explain Caching, I did'nt realize to look in the config screen before submitting a issue.

**Comment by shedaniel** [comment]
64 is a lot of blocks tho, you are probably caching 9x9, 81 chunks, and rendering those all, therefore the performance hit.
