### ISSUE TITLE
This mod breaks replay mod GUI elements

### ISSUE THREAD

**Issue by tkkot** [shedaniel/LightOverlay-Fabric#50]
Mc version: 1.16.1
Light overlay mod version: Fabric 5.4.1
Replay mod verions: 2.4.0

When using this mod together with the replay mod, certain replay mod elements disappear. For example in the pause menu there should be 2 buttons: Start/stop replay and pause/resume replay. They are missing. When I remove the overlay mod, they reappear. There is another element missing: In the world selection and server selection screens there should be an option saying "Record Singleplayer" or "Record Multiplayer".

### With the light overlay mod:
![obraz](https://user-images.githubusercontent.com/38937849/88049316-36c8a800-cb55-11ea-8e59-2b58aa8583cc.png)

### Without the light overlay mod:
![obraz](https://user-images.githubusercontent.com/38937849/88049742-eef65080-cb55-11ea-8928-ba5d509ea94d.png)

**Comment by shedaniel** [comment]
This is quite impossible, LightOverlay doesn't touch the gui

**Comment by tkkot** [comment]
But there is some conflict. How will you exlpain the fact that when I add this mod the GUI elements disappear and when I remove it they appear again?
