### ISSUE TITLE
Light Overlay with Sodium causes immense Lag

### ISSUE THREAD

**Issue by Fisch37** [shedaniel/LightOverlay-Fabric#52]
I have a Geforce 1050Ti, the Fabric Build 204 with Sodium (0.1.0) and Light Overlay (5.4.1). In this case when I am trying to use Light Overlay, the whole game just lags as hell. I sometimes even get the FPS number 0 (which is of course because of rounding).
More information I don't think there is to give. I am not getting an error in the log or an warning.

**Comment by shedaniel** [comment]
what's your range in light overlay. if it's above 16, please enable caching in light overlay

**Comment by Fisch37** [comment]
I actually somehow had range 32, which I found out after managing to work out that I would needed Mod Menu. I don't know how it started out on 32 either. I now reset all the options and it seems to work

**Comment by shedaniel** [comment]
alright, if you want the 32 range back, remember to enable caching
