### ISSUE TITLE
Missing license field causes Forge to crash on start

### ISSUE THREAD

**Issue by douira** [shedaniel/LightOverlay-Fabric#53]
Forge now throws a fatal error if a mod is missing the `license` field in the `mods.toml`. This is the same as https://github.com/shedaniel/cloth-config/issues/60
Here's some interesting info: https://forums.minecraftforge.net/topic/89070-forge-server-wont-start-with-mods-in-fodler/
The exact error is: `[java.lang.ThreadGroup:uncaughtException:1052]: net.minecraftforge.fml.loading.moddiscovery.InvalidModFileException: Missing License, please supply a license. (light-overlay-5.4.1.jar)`

**Comment by shedaniel** [comment]
isn't this just required in the 1.16.2 version?

**Comment by douira** [comment]
Forge seems to require it in the 1.16.2 version but was already displaying warnings in older versions. If you don't want to give a license, you could still fill the field with a placeholder string. (Although it's strongly recommended you choose a license since the code is already public)

**Comment by shedaniel** [comment]
Light Overlay is licensed under Apache 2.0. I just don't want to recompile for 1.16.1 to simply add a license field.

**Comment by douira** [comment]
No I'm just saying you can add the license field and then it's included the next time you release it to enable the next release to run on 1.16.2.
