### ISSUE TITLE
Crash when Caching disabled, no overlay when Caching enabled

### ISSUE THREAD

**Issue by boopidoop** [shedaniel/LightOverlay-Fabric#54]
When I press F7 with caching enabled, the overlay doesn't appear at all. I've tweaked all of the settings with no luck

When I press F7 with caching disabled (even on low reach), the screen turns black and the game crashes shortly after

**Comment by boopidoop** [comment]
Crash report finally decided to come up:

The game crashed whilst unexpected error
Error: java.lang.IllegalAccessError: tried to access field net.minecraft.class_4604.field_20995 from class me.shedaniel.lightoverlay.fabric.FrustumHelper

**Comment by shedaniel** [comment]
can you share your whole log

**Comment by boopidoop** [comment]
[crash-2020-08-19_02.43.51-client.txt](https://github.com/shedaniel/LightOverlay/files/5097088/crash-2020-08-19_02.43.51-client.txt)

**Comment by shedaniel** [comment]
incorrect version of light overlay on 1.16.1

**Comment by boopidoop** [comment]
I'm using 1.16.2, with the 1.16.2 version
