### ISSUE TITLE
Start up crash [Fabric] [1.16.2]

### ISSUE THREAD

**Issue by CyberFeast2K** [shedaniel/LightOverlay-Fabric#58]
I start up the game and I crash but it doesn’t give me a crash report so I have to go to the logs folder. Oh yeah and in the log one of the first thing it mentions is this mod so thought it had something to do with this mod. 
Crash report: https://pastebin.pl/view/9932d647

**Comment by shedaniel** [comment]
did you send the wrong log? that log you sent doesn't indicate that there is even a crash

**Comment by CyberFeast2K** [comment]
Nah that’s what it gives me when I crash. Oh yeah when I crash it says something about exit code: 0
