### ISSUE TITLE
Please include in the mod description and file name that this is a fabric mod.

### ISSUE THREAD

**Issue by ProsperCraft** [shedaniel/LightOverlay-Fabric#6]
I didn't realize it was until I installed it and it failed to load.

**Comment by Blayyke** [comment]
The mod categories should be enough no?

**Comment by ProsperCraft** [comment]
Unfortunately, no they still show up on the launcher when picking forge mods.  And a scan of the mod description doesn't state the dependancy on fabric which isn't supported on twitch.

**Comment by Blayyke** [comment]
Ah right I forget about the mess that is twitch launcher. Having fabric in the file name would be good.

**Comment by shedaniel** [comment]
It still says that it requires Fabric API in the description

**Comment by shedaniel** [comment]
I named the project with `(Fabric)`, this issue will be closed.

**Comment by ProsperCraft** [comment]
Thank you so much!
