### ISSUE TITLE
Mod Checks if presented on Server showing Uncompatibility on Multiplayer screen

### ISSUE THREAD

**Issue by Okimo** [shedaniel/LightOverlay-Fabric#66]
So this is minor issue as connection is still possible but its annoyance showing "Server mod list is not compatible" until mod is presented on server.

Forge: forge-1.16.3-34.1.24
Mod version: light-overlay-5.5.3

`[22Oct2020 19:25:38.966] [Netty Client IO #0/DEBUG] [net.minecraftforge.fml.client.ClientHooks/CLIENTHOOKS]: Received FML ping data from server at 192.168.0.147: FMLNETVER=2, mod list is compatible : false, channel list is compatible: true, extra server mods: {}
[22Oct2020 19:25:38.966] [Netty Client IO #0/INFO] [net.minecraftforge.fml.client.ClientHooks/CLIENTHOOKS]: Client has mods that are missing on server: [lightoverlay-forge]`

Old issue that brought me here searching for mod causing it:

> But apart from that these mods should be aware of the fact that they're supposed to be client side only. However they're naughty and do not override the DISPLAYTEST extensionpoint, where they would have the option of not interfering with the client compatibility checking. So if you want this fixed and the mods can't simply be put onto the server, go yell at their authors.

https://github.com/MinecraftForge/MinecraftForge/issues/6329#issuecomment-558387949

**Comment by shedaniel** [comment]
Fixed in 5.5.4, thanks for reporting!
