### ISSUE TITLE
1.14.3 fabric Light level Indicator showing well in a mushroom biome

### ISSUE THREAD

**Issue by Kylebartaous** [shedaniel/LightOverlay-Fabric#7]
Seems well in a mushroom Biome, it is showing the yellow x's that, mobs could possibly spawn there. Could be detection isn't picking it up as something that spawn-able, also since the biome name changed from mushroom_island -> mushroom_fields, & the shore lines -> mushroom_field_shore.

**Comment by Kylebartaous** [comment]
Could also need to factor that fix in for forge version.

**Comment by shedaniel** [comment]
Please test on the new update:
Fabric: v1.2.1
Forge: v1.1

**Comment by shedaniel** [comment]
Closing this issue, please create another issue if this continues to occur.
