### ISSUE TITLE
5.6.0 reports fabric-api >=0.29.1 requirement even when fabric-api 0.29.1 is installed

### ISSUE THREAD

**Issue by SimbaMCO** [shedaniel/LightOverlay-Fabric#72]
Attempting to launch Minecraft 1.16.4 with Fabric Loader 0.10.8 and with the following mods in the mods folder:

`fabric-api-0.29.1+1.16.jar`
`light-overlay-5.6.0.jar`

The log shows that the following mods are installed:

  [✔️] fabric-api-0.29.1+1.16
  [✔️] light-overlay-5.6.0

However, shortly afterward, the log produces the following error message:
`net.fabricmc.loader.discovery.ModResolutionException: Could not find required mod: lightoverlay requires {fabric-api @ [>=0.29.1]}`

Is a different version of fabric-api needed or is light-overlay's sanity checker just not detecting the version correctly?

**Comment by LiLi-Stormstout** [comment]
I am also experiencing this same exact error. :(
