### ISSUE TITLE
LightOverlay not showing up on vanilla server

### ISSUE THREAD

**Issue by BooperFish** [shedaniel/LightOverlay-Fabric#74]
Hi,
The light overlay is not showing up on a vanilla server. Since the mod is client-side, I am under the impression that it should work okay. I am running the latest JRE. The little status thing that says "light overlay" appears in the top left corner (as I think it probably should), and I can toggle it with F7, but nothing shows up. It works as expected in singleplayer.

![image](https://user-images.githubusercontent.com/77088851/103850863-5b1e2f80-5076-11eb-9a11-59080e4e346a.png)

**Comment by shedaniel** [comment]
Update architectury, plus, your room is well lit so there aren't any crosses.

**Comment by BooperFish** [comment]
Apologies- I apparently misunderstood how the mod worked. I walked in here just to take the screenshot, though. It looks to be working as expected. 

Thank you, sorry for the misfire.

**Comment by shedaniel** [comment]
No worries, enjoy the mod!
