### ISSUE TITLE
Light level only shows on blocks along the Z axis

### ISSUE THREAD

**Issue by UpcraftLP** [shedaniel/LightOverlay-Fabric#76]
For some reason, the light level is only shown on block positions where `X = 0`, see the screenshot.
I also went back to the coordinate origin to see whether they would show along the X axis, but that is not the case.

![image](https://user-images.githubusercontent.com/10714589/104831835-909ff580-588c-11eb-8d63-c1af4d1cee22.png)

Minecraft 1.16.4, with canvas renderer.

<details>
<summary>Mod List (Click to expand) </summary>

[✔️] architectury-1.3.80-fabric
  [✔️] canvas-mc116-1.0.1267
  [✔️] fabric-api-0.29.3+1.16
  [✔️] fabricmod_VoxelMap-1.10.14_for_1.16.4
  [✔️] illuminations-1.4.2
  [✔️] illuminations-uninstaller
  [✔️] light-overlay-5.6.1
  [✔️] lithium-fabric-mc1.16.4-0.6.0
  [✔️] Mesh-0.5.5-alpha.17+1.16.4
  [✔️] modmenu-1.14.13+build.19
  [✔️] okzoomer-4.0.1+1.16.2
  [✔️] phosphor-fabric-mc1.16.3-0.7.0+build.10
  [✔️] respackopts-1.3.1
  [✔️] RoughlyEnoughItems-5.8.10

</details>

**Comment by shedaniel** [comment]
is this sodium plus canvas

**Comment by UpcraftLP** [comment]
update: removing Canvas seems to fix the issue.

**Comment by gniftygnome** [comment]
This happens to me as well, but only with LightOverlay 5.6.0 and above.  Version 5.5.4 works like a charm.  So I hope nothing forces me to upgrade.

**Comment by gniftygnome** [comment]
FYI, this defect remains with Canvas mc116-1.0.1511 and Light Overlay 5.8.1.  Light Overlay 5.5.4 still works fine with the new Canvas version.

**Comment by gniftygnome** [comment]
Here's what spiralhalo commented in Canvas issue 199 ( https://github.com/grondag/canvas/issues/199#issuecomment-874476263 ):

> I have figured out the issue. LightOverlay uses accesswidener to access and compute frustum visibility directly.
> 
> To fix this in our side would require some superfluous computation in the render thread so I find it unlikely but would have to ask Grondag to be sure.
> 
> An easier solution is to ask LightOverlay to use the public function `Frustum.isVisible(Box)` to compute visibility as intended.

**Comment by spiralhalo** [comment]
I got in touch with Grondag and he determined it would be worth fixing it on Canvas's side. The frustum issue will hopefully be fixed in the next Canvas release. Thanks to everyone who reported and helped with this issue!

**Comment by shedaniel** [comment]
Thanks for the fix!
