### ISSUE TITLE
1.16.5 version still dosen't load on fabric

### ISSUE THREAD

**Issue by HalfKnightDrummer** [shedaniel/LightOverlay-Fabric#77]
Can't start the game with this mod saying:

Could not find required mod: lightoverlay requires {architectury @ [>=1.2.67]}

**Comment by triphora** [comment]
https://www.curseforge.com/minecraft/mc-mods/architectury-fabric

Or for Forge: https://www.curseforge.com/minecraft/mc-mods/architectury-forge
