### ISSUE TITLE
Fabric API problems

### ISSUE THREAD

**Issue by Teleskopis** [shedaniel/LightOverlay-Fabric#78]
I have an error: **Could not find required mod: lightoverlay requires {fabric-api @ [>=0.29.1]}**

I have tested with **lower** than 0.29.1, **the** 0.29.1 version, and **higher** than 0.29.1.

None of the versions work. it always shows that error message.

![Screenshot 2021-01-27 234720](https://user-images.githubusercontent.com/78114698/106058516-006a7780-60fa-11eb-8ca6-e0d28ba0f402.png)

**Comment by TheCherry** [comment]
Why is that closed? I have the same issue and I tested many different fabric-api versions.

**Comment by Dolphin2Point1** [comment]
you need to update your version of light overlay

**Comment by Dolphin2Point1** [comment]
also it was already tracked at #72

**Comment by Teleskopis** [comment]
Its overlaying with another mod. I think that's why it didn't work for me. As I realized that it was my issue - I closed it.
