### ISSUE TITLE
[1.14.4] Loading clientside code on the dedicated server.

### ISSUE THREAD

**Issue by ProsperCraft** [shedaniel/LightOverlay-Fabric#8]
I know this is a clientside mod, but if you could load only on the clientside then if players put it on the serverside it won't crash.

https://gist.github.com/ProsperCraft/3de44bb0df4128bc22dd62d1d98a886f

**Comment by shedaniel** [comment]
I will be fixing this hopefully today.

**Comment by shedaniel** [comment]
Fixed in v3.3.1
