### ISSUE TITLE
New dependency Architectury causes incompatibility with Voxelmap

### ISSUE THREAD

**Issue by StarsDown64** [shedaniel/LightOverlay-Fabric#80]
After updating to the most recent version of Light Overlay and getting Architectury, my Voxelmap kept crashing on startup. It stopped crashing when reverting this mod to <5.6.x and deleting Architectury. I'm not sure what the root cause of why Architectury and Voxelmap are incompatible, but I'm reporting it to Architectury if an issue doesn't already exist.

**Comment by StarsDown64** [comment]
https://github.com/architectury/architectury-api/issues/35

**Comment by shedaniel** [comment]
Not my problem, report to architectury
