### ISSUE TITLE
Latest fabric loader not loading when mod is in mods folder

### ISSUE THREAD

**Issue by CSTufts** [shedaniel/LightOverlay-Fabric#9]
when I add this mod, the loader is failing to open the game. Not sure what is going on with it. 

I have attached a log for you. let me know if its a conflict with something that I am running.
[2019-08-02-6 - success.log](https://github.com/shedaniel/LightOverlay-Fabric/files/3460594/2019-08-02-6.-.success.log)
[2019-08-02-5 - failure.log](https://github.com/shedaniel/LightOverlay-Fabric/files/3460595/2019-08-02-5.-.failure.log)

**Comment by shedaniel** [comment]
It is not even light overlay, it is optifabric’s issue, put the optifine jar in the mods folder

**Comment by CSTufts** [comment]
added as you suggested, sorry caught that after the fact... was in the middle of upgrading as I figured your mod needed the latest version as it was failing in 1.14.3

here is a failure log. the client never actually launches
thanks
[latest.log](https://github.com/shedaniel/LightOverlay-Fabric/files/3460775/latest.log)

**Comment by shedaniel** [comment]
How did you determine that it never launches? Check modmenu?

**Comment by CSTufts** [comment]
I mean the game simply doesn't launch, I put the mod in the mods folder and start minecraft the window never loads, take it out of the mods folder, game starts normally... is there a config file that I need to create, the loader usually handles a default file if one doesn't exist...

I am more than willing to help debug it, though I really have no java experience (sfdc apex for close to 10 years though, which is generally close enough...)

let me know if you need anything else, I can zip the mods folder if you need it

thanks

**Comment by shedaniel** [comment]
Okay in the log, the LWJGL (The Java OpenGL wrapper) is just starting up and the log stops, it would be nice if you can zip the mods folder.

**Comment by CSTufts** [comment]
[mods.zip](https://github.com/shedaniel/LightOverlay-Fabric/files/3461398/mods.zip)
I am running a mac osx 10.13.6
and 
the latest fabric loader 
fabric-loader-0.4.8+build.159-1.14.4

obviously can get you anything els that you need
cheers

**Comment by CSTufts** [comment]
hey I just actually got it to crash
here are the logs, 
I rebooted as minecraft was complaining that there were other instances running. 

I also just added the mod by itself, hope this helps
[latest.log](https://github.com/shedaniel/LightOverlay-Fabric/files/3461431/latest.log)

**Comment by shedaniel** [comment]
Oops, you need Fabric API: https://www.curseforge.com/minecraft/mc-mods/fabric-api

**Comment by CSTufts** [comment]
hey following up, I had fabric installed (not when I ran that test though). I have installed your latest version and its working as expected.
thanks
