### ISSUE TITLE
number light level overlay get bugged on fabric

### ISSUE THREAD

**Issue by omar-shams-png** [shedaniel/LightOverlay-Fabric#97]
when i turned the light level overlay to numbers every time i stop looking under me the numbers turn to glitched block.
![2021-05-26_15 09 04](https://user-images.githubusercontent.com/57365586/119657315-6bbc2000-be34-11eb-8f2d-eb4b3738f9ec.png)
![2021-05-26_15 08 55](https://user-images.githubusercontent.com/57365586/119657322-6d85e380-be34-11eb-9dc8-4c35931cce06.png)

**Comment by shedaniel** [comment]
Remove optifine to check if it is an optifine issue

**Comment by omar-shams-png** [comment]
> Remove optifine to check if it is an optifine issue

i tried and yes it is an optifine issue, thanks.
but will there be a new update to this mod that fixes it?

**Comment by shedaniel** [comment]
No, see #5
